ci: Fix GPU job not actually enabling OptiX
AcademySoftwareFoundation/OpenShadingLanguage pull request #1738
Opened 2023-10-02 23:24 UTC by brechtvl

## Description

In #1668 USE_OPTIX changed to OSL_USE_OPTIX, but CI was not updated.

## Tests

N/A

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [x] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

2023-10-02 23:27 UTC, lgritz approved these changes

2023-10-02 23:52 UTC, lgritz requested changes
Oof, something is broken here

2023-10-02 23:58 UTC, AlexMWells commented
```
 Found CUDA 11.8 
 ...
clang-15: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]

```
So does the clang version need to be paired up with CUDA version?  Meaning CUDA 11.5 is newest that could be used when using clang-15?
And similar pairings might be true of different clang versions?

2023-10-03 00:50 UTC, brechtvl commented
The GPU job is failing because CPU flags `-mavx2 -mf16c` are part of the command for building CUDA bitcode, which in turns makes the Imath `half.h` header try to use CPU intrinsics.

2023-10-03 01:11 UTC, brechtvl commented
That seems to have fixed it. Other CI failures are unrelated.

> So does the clang version need to be paired up with CUDA version? Meaning CUDA 11.5 is newest that could be used when using clang-15?
> And similar pairings might be true of different clang versions?

CUDA 11.8 + LLVM 15 works fine for me despite the warning. But in general, I guess so.

2023-10-03 05:34 UTC, lgritz approved these changes
LGTM

2023-10-03 05:34 UTC, merged